homework/urls.py
from django.urls import path
from . import handler

app_name = "homework"

urlpatterns = [
    path("", handler.HomeWorkView.as_view(), name="index"),
    path("register/", handler.homework_register, name="register"),
    path("delete/", handler.homework_delete, name="delete"),
    path("done/", handler.homework_done, name="done"),
    path("<homework_id>/result/", handler.HomeWorkResult.as_view(), name="result"),
    path("<homework_id>/result/<int:student_id>/", handler.HomeWorkResult.as_view(), name="student_result"),
    path("<homework_id>/", handler.HomeWorkDetailView.as_view(), name="detail"),
    path("<homework_id>/start/", handler.HomeWorkStart.as_view(), name="start"),
]

question/urls.py
from django.urls import path
from . import handler

app_name = "question"
urlpatterns = [
    path("register/", handler.question_register, name="register"),
    path("delete/", handler.question_delete, name="delete"),
    path("answer/register/", handler.answer_register, name="answer"),
    path("answer/delete/", handler.answer_delete, name="answer_delete"),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("web_account.urls")),
    path("student/", include("student.urls")),
    path("teacher/", include("teacher.urls")),
    path("class/", include("school_class.urls")),
    path("home_work/", include("homework.urls")),
    path("question/", include("question.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.http import request
from django.urls.base import reverse
from django.utils import timezone
import datetime

import homework

User = get_user_model()

class Profile(models.Model):
    img = models.ImageField(upload_to="profile", blank=True, null=True)
    user = models.OneToOneField(User, models.CASCADE)
    role = models.CharField(
        max_length=10,
        choices=(("teacher", "teacher"), ("student", "student")),
        help_text="are you a student or teacher",
    )

    @property
    def role_name(self):
        match self.role:
            case "teacher":
                return self.teacher.name
            case "student":
                return self.student.name
        

    def get_role_model(self):
        try:
            if self.role == "teacher":
                return self.teacher
            else:
                return self.student
        except Exception:
            return None

    def get_role_register_url(self):
        match self.role:
            case "teacher":
                return reverse("teacher:register")
            case "student":
                return reverse("student:register")

    def delete(self, using=None, keep_parents=False):
        print("deleting")
        return super().delete(using, keep_parents)


class Teacher(models.Model):
    name = models.CharField(max_length=30, unique=True)
    gender = models.CharField(max_length=1, choices=(("m", "man"), ("w", "woman")))
    phone = models.CharField(max_length=10, blank=True, null=True)
    profile = models.OneToOneField(Profile, models.CASCADE)

    def __str__(self):
        return str(self.name)


class Student(models.Model):
    name = models.CharField(max_length=30, unique=True)
    phone = models.CharField(max_length=10, blank=True, null=True)
    gender = models.CharField(max_length=1, choices=(("m", "man"), ("w", "woman")))
    nisn = models.CharField(max_length=20, help_text="nomor induk siswa")
    profile = models.OneToOneField(Profile, models.CASCADE)

    def __str__(self):
        return self.name

    def has_answered_homework(self, homework):
        "return none if not answered"
        return self.homeworkanswer_set.filter(homework=homework).first() != None


class Class(models.Model):
    class_name = models.CharField(max_length=20)
    teacher = models.ForeignKey(Teacher, models.CASCADE)
    description = models.TextField(blank=True, null=True)
    requests = models.ManyToManyField(Student, "class_request", blank=True)
    accepted = models.ManyToManyField(Student, "class_accepted", blank=True)
    excerpt = models.CharField(max_length=100)
    img = models.ImageField(upload_to="class", blank=True, null=True)

    def __str__(self):
        return str(self.class_name + " {}".format(self.teacher))

    def student_accepted(self, student):
        "return true if student models exists in accepted field"
        if not student: return False
        return self.accepted.filter(id=student.id).first() != None


class HomeWork(models.Model):
    _class = models.ForeignKey(Class, models.CASCADE)
    name = models.CharField(max_length=20)
    description = models.TextField(blank=True, null=True)
    done = models.BooleanField(default=False)
    expire = models.DateTimeField()
    added_at = models.DateTimeField(auto_now_add=True)

    def created(self):
        timedelta: datetime.timedelta = timezone.now()-self.added_at
        if int(timedelta.days / 365):
            return f"{int(timedelta.days/365)}y"
        elif int(timedelta.days / 30):
            return f"{int(timedelta.days/30)}m"
        elif int(timedelta.days / 7):
            return f"{int(timedelta.days/7)}w"
        elif int(timedelta.days):
            return f"{timedelta.days}d"
        elif int(timedelta.seconds / (60 * 60)):
            return f"{int(timedelta.seconds/(60*60))}h"
        elif int(timedelta.seconds / 60):
            return f"{int(timedelta.seconds/60)}m"
        else:
            return f"{timedelta.seconds}s"

    def time_to_expire(self):
        timedelta: datetime.timedelta = self.expire-timezone.now()
        if int(timedelta.days / 365):
            return f"{int(timedelta.days/365)}y"
        elif int(timedelta.days / 30):
            return f"{int(timedelta.days/30)}m"
        elif int(timedelta.days / 7):
            return f"{int(timedelta.days/7)}w"
        elif int(timedelta.days):
            return f"{timedelta.days}d"
        elif int(timedelta.seconds / (60 * 60)):
            return f"{int(timedelta.seconds/(60*60))}h"
        elif int(timedelta.seconds / 60):
            return f"{int(timedelta.seconds/60)}m"
        else:
            return f"{timedelta.seconds}s"

    def students_homeworkanswer(self):
        pass

    def students_has_answer(self):
        "return student that has answered this homework"
        d=[]
        for x in self.homeworkanswer_set.all():
            d.append(x.student)
        return d

    def students_didnt_answer(self):
        "return student that didnt answered this homework"
        return self._class.accepted.exclude(id__in=[s.id for s in self.students_has_answer()])

    def homeworkanswer_from(self, student):
        return self.homeworkanswer_set.filter(student=student).first()

    def is_expire(self):
        return timezone.now() > self.expire

    def __str__(self):
        return self.name


class Question(models.Model):
    homework = models.ForeignKey(HomeWork, models.CASCADE)
    text = models.CharField(max_length=100)

    def __str__(self):
        return self.text


class Answer(models.Model):
    text = models.CharField(max_length=100)
    question = models.ForeignKey(Question, models.CASCADE)
    is_true = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class HomeWorkAnswer(models.Model):
    student = models.ForeignKey(Student, models.CASCADE)
    homework = models.ForeignKey(HomeWork, models.CASCADE)

    def selected_answer(self, question):
        d=self.answerquestion_set.filter(question=question).first()
        if d != None:
            return d.answer
        return None

    def right_answer(self):
        d=[]
        for a in self.answerquestion_set.all():
            if a.answer.is_true:
                d.append(a)
        return d


class AnswerQuestion(models.Model):
    question = models.ForeignKey(Question, models.CASCADE)
    answer = models.ForeignKey(Answer, models.CASCADE)
    homework_answer = models.ForeignKey(HomeWorkAnswer, models.CASCADE)

homework/models.py
from django.db import models

# Create your models here.

homework/forms.py
from django import forms
from core import models


class HomeWorkForm(forms.ModelForm):
    class Meta:
        model = models.HomeWork
        fields = ["name", "description", "expire"]

templates/homework/answer.html
{% extends 'skeleton/base.html' %}
{% block body %}
<div class="p-5">
	<h2 class="h-20 flex items-center justify-center text-xl">
	{{ homework }}
	</h2>
	{% if has_answered_homework  %}
	<p>
		you already answered this homework
	</p>
	<p>
	{{ homework.description|default:"" }}
	</p>
	<a href="{% url 'homework:result' homework.id %}">
		<button class="btn">check result</button>
	</a>
	{% else %}
	<form method="post" class="px-4">
		{% csrf_token %}
		{% for question in homework.question_set.all %}
		<label for="{{ question.id }}">
			{{ forloop.counter }}. {{ question }}
		</label>
		<ol class="px-1 list-inside list-[upper-alpha]">
			{% for answer in question.answer_set.all %}
			<li>
			<label for="{{ question.id }}">
				{{ answer }}
			</label>
			<input id="{{ question.id }}" type="radio" name="{{ question.id }}" value="{{ answer.id }}">
			</li>
			{% endfor %}
		</ol>
		{% endfor %}
		<button class="btn">send</button>
	</form>
	{% endif %}
</div>
{% endblock %}

templates/homework/detail.html
{% extends 'skeleton/base.html' %}
{% load core %}
{% block body %}
<div class="p-5">
	<div class="mb-2">
		<h2 class="h-10 text-2xl flex items-center justify-center">{{ homework }}</h2>
		<p class="indent-5">{{ homework.description|default:"" }}</p>
		<small>total question {{ homework.question_set.all|length }}</small>
	</div>
	{% if request.user.profile.role == 'student' %}
		{% if homework.done %}
			{% call request.user.profile.student "has_answered_homework" homework=homework as has_answered_homework %}
			{% if has_answered_homework %}
			<a href="{% url 'homework:result' homework.id %}"><button class="btn">result</button></a>
			{% else %}
				{% if homework.is_expire %}
				<strong>you not answer this homework</strong>
				{% else %}
				<a href="{% url 'homework:start' homework.id %}"><button class="btn">start</button></a>
				{% endif %}
			{% endif %}
		{% endif %}
	{% elif request.user.profile.role == 'teacher' %}
		{% if homework.done %}
		<a class="btn" href="{% url 'homework:result' homework.id %}">
			results
		</a>
		{% else %}
		<form class="form" action="{% url 'question:register' %}" method="post">
			<input class="input" type="hidden" name="homework" value="{{ homework.id }}">
			<label for="input-question">
				question text:
			</label>
			<input id="input-question" class="input" name="text">
			<button class="btn">add</button>
		</form>
		{% endif %}
		<ol class="my-2">
		{% for question in homework.question_set.all %}
			<li>
				<div class="flex items-center justify-between text-xl">
					{{ forloop.counter }}. {{ question }}
					{% if not homework.done %}
					<form method="post" action="{% url 'question:delete' %}">
						{% csrf_token %}
						<input type="hidden" name="question" value="{{ question.id }}">
						<button class="btn">delete</button>
					</form>
					{% endif %}
				</div>
				<ol class="px-2 mb-5">
			{% for answer in question.answer_set.all %}
					<li class="flex items-center justify-between">
						<div class="text-sm">
							{% char forloop.counter0	%}. {{ answer }}
							{% if answer.is_true %}
							<i class="fa-solid fa-circle-check text-green-400"></i>
							{% endif %}
						</div>
						{% if not homework.done %}
						<form action="{% url 'question:answer_delete' %}" method="post">
							{% csrf_token	%}
							<input type="hidden" name="answer" value="{{ answer.id }}">
							<button class="btn">delete</button>
						</form>
						{% endif %}
					</li>
			{% endfor %}
				</ol>
				{% if not homework.done %}
				<form class="form" action="{% url 'question:answer' %}" method="post">
					{% csrf_token %}
					<input class="input" type="hidden" name="question" value="{{ question.id }}">
					<label for="input-box">
						text:
					</label>
					<input id="input-box" class="input" name="text">
					<label>
						is_true
					</label>
					<input type="checkbox" name="is_true">
					<button class="btn">add answer</button>
				</form>
				{% endif %}
			</li>
		{% endfor %}
		</ol>
	{% endif %}
</div>
{% endblock	%}

templates/homework/result.html
{% extends 'skeleton/base.html' %}
{% load core %}
{% block body %}
	<div class="p-5">
		<h2 class="text-4xl my-2">
			homework {{ homework }}
		</h2>
		<p>
			{{ homework.description|default:"" }}
		</p>
		<h3>
			total question {{ homework.question_set.all|length }}
		</h3>
		{% if request.user.profile.role == 'student' %}
		<h3>
			right question {{ homework_answer.right_answer|length }}
		</h3>
		<p>
			<i class="fa-solid fa-circle-check text-green-400"></i> : right answer
			<br>
			<i class="fas fa-circle-x"></i> : selected answer
		</p>
			<ol>
			{% for question in homework.question_set.all %}
				<li>
					<h4 class="text-xl">
						{{ forloop.counter }}. {{ question }}
					</h4>
				<ol class="list-inside list-[upper-alpha] px-3">
				{% for answer in question.answer_set.all %}
					<li >
						{{ answer }}
					{% if  answer.is_true %}
						<i class="fa-solid fa-circle-check text-green-400"></i>
					{% endif %}
					{% call homework_answer "selected_answer" question as selected	%}
					{% if selected == answer %}
					<i class="fas fa-circle-x"></i>
					{% endif %}
					</li>
				{% endfor %}
				</ol>
				</li>
			{% endfor %}
			</ol>
		{% elif request.user.profile.role == 'teacher' %}
		<ul class="list-inside">
			{% for student in homework.students_has_answer %}
			<li>
				{{ student }}
			</li>
			{% endfor %}
		</ul>
		{% endif %}
	</div>
{% endblock %}

templates/homework/student_result.html
{% extends 'skeleton/base.html' %}
{% load core %}
{% block body %}
<div class="p-5">
	<h2 class="text-4xl my-2">
		homework {{ homework }}
	</h2>
	<p>
		{{ homework.description|default:"" }}
	</p>
	<h3>
		total question {{ homework.question_set.all|length }}
	</h3>
	<h3>
		right question {{ homeworkanswer.right_answer|length }}
	</h3>
	<p>
		<i class="fa-solid fa-circle-check text-green-400"></i> : right answer
		<br>
		<i class="fas fa-circle-x"></i> : selected answer
	</p>
		<ol>
		{% for question in homework.question_set.all %}
			<li>
				<h4 class="text-xl">
					{{ forloop.counter }}. {{ question }}
				</h4>
			<ol class="list-inside list-[upper-alpha] px-3">
			{% for answer in question.answer_set.all %}
				<li >
					{{ answer }}
				{% if  answer.is_true %}
					<i class="fa-solid fa-circle-check text-green-400"></i>
				{% endif %}
				{% call homeworkanswer "selected_answer" question as selected	%}
				{% if selected == answer %}
				<i class="fas fa-circle-x"></i>
				{% endif %}
				</li>
			{% endfor %}
			</ol>
			</li>
		{% endfor %}
		</ol>
</div>
{% endblock %}