homework/urls.py
from django.urls import path
from . import handler

app_name = "homework"

urlpatterns = [
    path("", handler.HomeWorkView.as_view(), name="index"),
    path("register/", handler.homework_register, name="register"),
    path("delete/", handler.homework_delete, name="delete"),
    path("done/", handler.homework_done, name="done"),
    path("<homework_id>/result/", handler.HomeWorkResult.as_view(), name="result"),
    path("<homework_id>/result/<int:student_id>/", handler.HomeWorkResult.as_view(), name="student_result"),
    path("<homework_id>/", handler.HomeWorkDetailView.as_view(), name="detail"),
    path("<homework_id>/start/", handler.HomeWorkStart.as_view(), name="start"),
]

school_class/urls.py
from django.urls import path, include
from . import handler

app_name = "class"
urlpatterns = [
    path("register/", handler.ClassRegister.as_view(), name="register"),
    path("requests/", handler.StudentClassRequest.as_view(), name="requests"),
    path("<id>/requests/", handler.ClassRequests.as_view(), name="class_requests"),
    path("students/<id>/accept/", handler.accept_class, name="accept"),
    path("students/<id>/delete/", handler.delete_class, name="remove_student"),
    path("<id>/students/", handler.ClassMember.as_view(), name="students"),
    # path('<id>/exit/', handler.exit_class, name='exit_class'),
    path("<pk>/", handler.ClassDetail.as_view(), name="detail"),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("web_account.urls")),
    path("student/", include("student.urls")),
    path("teacher/", include("teacher.urls")),
    path("class/", include("school_class.urls")),
    path("home_work/", include("homework.urls")),
    path("question/", include("question.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_account/urls.py
from django.urls import path
from . import handler

app_name = "account"

urlpatterns = [
    path("login/", handler.Login.as_view(), name="login"),
    path("logout/", handler.logout, name="logout"),
    path("register/", handler.Register.as_view(), name="register"),
    path("profile/", handler.Profile.as_view(), name="profile"),
    path("reset/", handler.reset, name="reset"),
    path("settings/", handler.SettingView.as_view(), name="settings"),
    path("<pk>/", handler.Detail.as_view(), name="detail"),
]

school_class/forms.py
from django import forms
from core import models


class ClassRegisterFormTeacher(forms.ModelForm):
    class Meta:
        model = models.Class
        fields = ["class_name", "description", "excerpt", "img"]


class ClassRegisterFormStudent(forms.Form):
    class_choices = forms.IntegerField(widget=forms.Select)

    def __init__(self, teacher_id=None, joined_class=[], *args, **kwargs):
        super().__init__(*args, **kwargs)
        teacher = None
        try:
            teacher = models.Teacher.objects.get(id=teacher_id)
        except Exception as e:
            pass
        if teacher:
            choices = ((c.id, c) for c in models.Class.objects.filter(teacher=teacher))
        else:
            choices = (
                (c.id, c) for c in models.Class.objects.exclude(id__in=joined_class)
            )
        self.fields["class_choices"].widget.choices = choices

school_class/views.py
from django.shortcuts import render

# Create your views here.

templates/school_class/class_detail.html
{% extends 'skeleton/base.html' %}
{% load core %}
{% block body %}
<div class="pt-5">
	<div class="w-80 h-60 bg-blue-400 rounded-tr-full rounded-br-full overflow-hidden shadow-md border-2 border-l-0 border-slate-200">
		{% if object.img %}
		<img class="w-full h-full object-cover" src="{% media object.img.name %}">
		{% endif %}
	</div>
	<div class="px-2 max-w-lg m-auto">
		<div class="sm:flex items-center">
			<h1 class="text-8xl my-10 mr-5">{{ object.class_name }}</h1>
			<div>
				<h4 class="text-2xl">{{ object.excerpt }}</h4>
				<small class="text-black/50">teacher: <a href="{% url 'account:detail' object.teacher.profile.user.id %}" class="underline">{{ object.teacher }}</a></small>
			</div>
		</div>
		<div class="my-5 flex flex-wrap gap-2">
			{% if object.teacher == request.user.profile.teacher %}
			<a class="btn" href="{% url 'class:class_requests' object.id %}">requests</a>
			<a class="btn" href="{% url 'class:students' object.id %}">member</a>
			{% else %}
				{% if object in user.profile.student.class_accepted.all %}
				<a class="btn" href="{% url 'class:remove_student' object.id %}">exit class</a>
				{% elif object in user.profile.student.class_request.all %}
				<a class="btn" href="{% url 'class:remove_student' object.id %}">
					cancel request
				</a>
				{% else %}
				<form method="post" action="{% url 'class:register' %}">
					{% csrf_token %}
					<input class="hidden" name="class_choices" value="{{ object.id }}">
					<button class="btn">join</button>
				</form>
				{% endif %}
			{% endif %}
			<form action="{% url 'homework:index' %}">
				<input type="hidden" name="class" value="{{ object.id }}">
				<button class="btn">homework</button>
			</form>
		</div>
		<p class="text-xl indent-5 my-5">{{ object.description }}</p>
	</div>
</div>
{% endblock %}

templates/school_class/class_list.html
{% extends 'skeleton/base.html' %}
{% block body %}
<div class="p-5">
	<ul>
	{% for class in object_list %}
	<li class="flex items-center justify-between border-y">
		<a href="{% url 'class:detail' class.id %}">
			<h3>
				{{ class }}
			</h3>
			<a href="{% url 'class:delete' class.id %}">
					<button class="btn">cancel request</button>
				</a>
		</a>
	</li>
	{% endfor %}
	</ul>
</div>
{% endblock %}

templates/school_class/class_member_list.html
{% extends 'skeleton/base.html'	%}
{% load core %}
{% block body %}
<div class="p-3 flex flex-col gap-3">
	<h2 class="text-4xl font-bold my-5 text-center">Class Member</h2>
	{% if object_list|length < 1 %}
	<h3 class="text-center text-xl">NO MEMBER</h3>
	{% endif %}
	{% for student in object_list %}
	<div class="flex items-center gap-3">
		<div class="w-20 h-20 bg-gray-300 rounded-full overflow-hidden flex items-center justify-center">
			{% if student.profile.img %}
			<img class="w-full h-full object-cover" src="{% media student.profile.img.name %}">
			{% else %}
			<i class="fas fa-user text-5xl text-white"></i>
			{% endif %}
		</div>
		<div class="flex flex-col gap-2">
			<h3 class="text-xl font-bold tracking-wide">{{ student }}</h3>
			<div class="">
				<a href="{% url 'account:detail' student.profile.user.id %}">
					<button class="w-32 p-1 rounded-md bg-blue-500 text-white">info</button>
				</a>
				<form class="inline-block" method="post" action="{% url 'class:remove_student' class.id %}?next={% url 'class:students' class.id %}">
					{% csrf_token %}
					<input type="hidden" name="student" value="{{ student.id }}">
					<button class="w-32 p-1 rounded-md bg-gray-200">remove</button>
				</form>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

templates/school_class/class_request_list.html
{% extends 'skeleton/base.html'	%}
{% load core %}
{% block body %}
<div class="p-3 flex flex-col gap-3">
	<h2 class="text-4xl font-bold my-5 text-center">Class Request</h2>
	{% if object_list|length < 1 %}
	<h3 class="text-center text-xl">NO REQUEST</h3>
	{% endif %}
	{% for student in object_list %}
	<div class="flex items-center gap-3">
		<div class="w-20 h-20 bg-gray-300 rounded-full overflow-hidden flex items-center justify-center">
			{% if student.profile.img %}
			<img class="w-full h-full object-cover" src="{% media student.profile.img.name %}">
			{% else %}
			<i class="fas fa-user text-5xl text-white"></i>
			{% endif %}
		</div>
		<div class="flex flex-col gap-2">
			<h3 class="text-xl font-bold tracking-wide">{{ student }}</h3>
			<div class="">
				<form class="inline-block" method="post" action="{% url 'class:accept' class.id %}?next={% url 'class:class_requests' class.id %}">
					{% csrf_token %}
					<input type="hidden" name="student" value="{{ student.id }}">
					<button class="w-32 p-1 rounded-md bg-blue-500 text-white">accept</button>
				</form>
				<form class="inline-block" method="post" action="{% url 'class:remove_student' class.id %}?next={% url 'class:students' class.id %}">
					{% csrf_token %}
					<input type="hidden" name="student" value="{{ student.id }}">
					<button class="w-32 p-1 rounded-md bg-gray-200">remove</button>
				</form>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

templates/school_class/home_work_list.html
{% extends 'skeleton/base.html' %}
{% block body %}
<h2 class="text-center text-4xl py-5">homework</h2>
<ul class="flex flex-wrap items-center justify-center gap-3">
	{% for homework in object_list %}
	{% if homework.done or request.user.profile.role == 'teacher' %}
	<li>
		<a href="{% url 'homework:detail' homework.id %}">
			<div class="transition-all duration-300 w-40 h-16 border p-3 rounded-md hover:bg-blue-50 hover:border-blue-400 flex gap-3 items-center relative [&>.nav]:hover:-translate-y-full [&>.nav]:hover:opacity-100 [&>.nav]:hover:shadow-md shadow-lg hover:shadow-none">
				<h4>
					{{ homework }}
				</h4>
				<div class="flex flex-col child:text-[10px] child:text-black/50">
					{% if not homework.is_expire %}
					<small>
						{{ homework.time_to_expire }} before result
					</small>
					{% else %}
						{% if homework.done %}
						<small>done</small>
						{% else %}
						<small>expire</small>
						{% endif %}
					{% endif %}
					<small>
						created {{ homework.created }} ago
					</small>
				</div>
				{% if request.user.profile.role == 'teacher' %}
				<div class="absolute top-[-10%] -translate-y-[200%] left-0 w-full h-full rounded-md nav transition-all ease-in-out opacity-0 shadow-none bg-gray-50 border flex flex-wrap items-center p-3 gap-3">
					<form method="post" action="{% url 'homework:delete' %}">
						{% csrf_token %}
						<input name="homework" value="{{ homework.id }}" type="hidden">
						<button class="peer"><i class="fas fa-circle-x"></i></button>
						<div class="peer-hover:translate-y-1 peer-hover:top-full peer-hover:opacity-100  w-full h-min transition-all duration-300 opacity-0 absolute top-full left-0 bg-white px-3 rounded-sm shadow-md text-sm">delete homework</div>
					</form>
					{% if not homework.done %}
					<form method="post" action="{% url 'homework:done' %}">
						{% csrf_token %}
						<input name="homework" value="{{ homework.id }}" type="hidden">
						<button class="peer"><i class="fas fa-circle-check"></i></button>
						<div class="peer-hover:translate-y-1 peer-hover:top-full peer-hover:opacity-100  w-full h-min transition-all duration-300 opacity-0 absolute top-full left-0 bg-white px-3 rounded-sm shadow-md text-sm">submit homework</div>
					</form>
					{% endif %}
				</div>
				{% endif %}
			</div>
		</a>
	</li>
	{% endif %}
	{% endfor %}
{% if request.user.profile.role == 'teacher' %}
	<li>
		<div id="add-homework" class="transition-all duration-300 w-40 h-16 border p-3 rounded-md hover:bg-blue-50 hover:border-blue-400 flex gap-3 items-center relative [&>.nav]:hover:-translate-y-full [&>.nav]:hover:opacity-100 [&>.nav]:hover:shadow-md justify-center [&>*]:hover:text-blue-400 shadow-lg hover:shadow-none">
					<i class="far text-slate-300 fa-circle-plus"></i>
				<dialog class="overflow-visible backdrop:backdrop-blur-lg">
					<form method="dialog" class="absolute top-0 right-0 -translate-y-1/2 translate-x-1/2 outline-none">
						<button><i class="fas fa-circle-x text-xl text-red-400"></i></button>
					</form>
					<h3 class="text-center text-xl">HomeWork Form</h3>
					<form class="form" action="{% url 'homework:register' %}" method="post">
						{% csrf_token %}
						<input class="hidden" name="class" value="{{ class.id }}">
						<div class="field">
							<h3 class="label">name:</h3>
							<input tabindex="1" name="name" class="input" required>
						</div>
						<div class="field">
							<h3 class="label">description:</h3>
							<input tabindex="2" name="description" class="input">
						</div>
						<div class="field">
							<h3 class="label">expire:</h3>
							<input tabindex="3" name="expire" class="input" type="date" required>
						</div>
						<button tabindex="4" class="btn">add homework</button>
					</form>
				</dialog>
			</div>
	</li>
{% endif %}
</ul>
<script>
	let add_homework = document.getElementById("add-homework")
	add_homework.onclick = ev => {
			let dialog = document.querySelector("dialog")
			dialog.showModal()
		}
</script>
{% endblock %}

templates/school_class/home_work_register.html
{% extends 'skeleton/base.html' %}
{% block body %}
<div class="h-screen w-screen bg-[#e3e3e3]">
	<div class="flex items-center justify-center p-10 font-bold text-lg">
		{{ title }}
	</div>
	{% if form.errors or error %}
	<dialog class="backdrop:backdrop-blur p-10 box-content scale-0 transition-all duration-300">
		<form method="dialog" class="flex-col flex items-center justify-center gap-2 rounded-sm">
			<div class="bg-red-50 rounded-md p-2">
				{% for t, error in form.errors.items %}
				<span>{{ t }}:</span>
				<p class="text-red-400 indent-2">{{ error }}</p>
				{% endfor %}
				<div>{{ error }}</div>
			</div>
			<button class="px-5 py-1 outline-none bg-blue-400 rounded-md shadow-md active:scale-95 active:shadow-none transition-all text-white border">ok</button>
		</form>
	</dialog>
	<script>
		let dialog = document.querySelector('dialog')
		dialog.showModal()
		dialog.classList.replace('scale-0', 'scale-100')
	</script>
	{% endif %}
	<form class="px-3 max-w-[500px] m-auto" method="post">
		{% csrf_token %}
		{% for field in form %}
		<div class="bg-white shadow-md rounded-md box-content p-5 mb-5">
			<div class="mb-3">
				<h3 class="text-lg text-black/80">
					{{ field.label }}
					{% if field.field.required %}
					<span class="text-sm text-red-400">*</span>
					{% endif %}
				</h3>
				<p class="text-sm text-black/50">{{ field.help_text }}</p>
			</div>
			{% if field.field.widget.input_type == 'select' %}
			<select
				class="w-full h-10 rounded-md transition-all duration-300 outline-none border-[1px] hover:border-b-[2px] hover:border-blue-400"
				name="{{ field.name }}"
				{% if field.field.required %}
				required
				{% endif %}
			>
				{% for option in field.field.widget.choices %}
				<option value="{{ option.0 }}">{{ option.1 }}</option>
				{% endfor %}
			</select>
			{% else %}
			<label>
				<input
					name="{{ field.name }}"
					type="{{ field.field.widget.input_type }}"
					class="w-full outline-none border-b-[2px] focus:border-blue-400"
					{% if field.value  %}
					value="{{ field.value }}"
					{% endif %}
					{% if field.field.required %}
					required
					{% endif %}
					>

			</label>
			{% endif %}	
		</div>
		{% endfor %}
		<button class="px-3 py-2 bg-blue-400 rounded-md shadow-md active:scale-95 active:shadow-none transition-all text-white border">submit</button>
	</form>
</div>
{% endblock %}