web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("web_account.urls")),
    path("student/", include("student.urls")),
    path("teacher/", include("teacher.urls")),
    path("class/", include("school_class.urls")),
    path("home_work/", include("homework.urls")),
    path("question/", include("question.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_account/urls.py
from django.urls import path
from . import handler

app_name = "account"

urlpatterns = [
    path("login/", handler.Login.as_view(), name="login"),
    path("logout/", handler.logout, name="logout"),
    path("register/", handler.Register.as_view(), name="register"),
    path("profile/", handler.Profile.as_view(), name="profile"),
    path("reset/", handler.reset, name="reset"),
    path("settings/", handler.SettingView.as_view(), name="settings"),
    path("<pk>/", handler.Detail.as_view(), name="detail"),
]

templates/skeleton/base.html
{% load static %}
{% load core %}

<!DOCTYPE html>
<html>
	<head>
		<title>{{ TITLE }}</title>
		<meta name="viewport" content="width=device-width,initial-scale=1" />
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />
		<link rel="stylesheet" href="{% static 'css/fontawesome.css' %}" />
	</head>
	<body class="bg-black/10">
		<input id="nav-toggle" type="checkbox" class="peer hidden" />
		<nav
			class="fixed top-1/2 left-0 -translate-x-full -translate-y-1/2 border h-[90vh] sm:h-[800px] sm:max-h-[90vh] w-[70vw] sm:w-60 bg-white rounded-[0_30px_30px_0] px-5 flex items-center justify-center flex-col [&>*:not(label)]:w-full z-[999] peer-checked:translate-x-0 transition duration-300 shadow-sm"
		>
			<label
				for="nav-toggle"
				class="absolute top-1/2 left-full w-10 h-10 border rounded-full -translate-x-1/2 flex items-center justify-center border-white bg-blue-400 shadow-[0_0_5px] shadow-black/20"
			></label>
			<div class="flex items-center justify-center py-5">
				<a href="/">
					<h2 class="text-3xl font-bold text-center h-fit w-full">Lorem</h2>
				</a>
			</div>
			<div class="h-full">
				<details class="[&>summary>i]:open:rotate-180">
					<summary
						class="border-b font-bold py-2 px-2 flex items-center justify-between"
					>
						<h3>ACCOUNT</h3>
						<i class="fa-regular fa-chevron-down transition"></i>
					</summary>
					<ul class="my-1 text-gray-600 text-sm">
						{% if request.user.is_authenticated %}
						<a
							href="{% url 'account:detail' request.user.id %}"
							class="py-1 px-2 bg-gray-300 rounded-md transition flex items-center my-1 shadow-lg active:scale-95 active:shadow-none"
						>
							{% if request.user.profile.img.name %}
							<img class="w-10 h-10 object-cover object-center rounded-full flex-shrink-0" src="{% media request.user.profile.img.name %}" alt="{{ request.user.profile.img.name }}">
							{% else %}
							<i class="h-10 w-10 fa-solid fa-circle-user text-4xl flex-shrink-0 text-black/30"></i>
							{% endif	%}
							<div class="w-full px-2 child:w-full flex flex-col child:h-5 items-center justify-center">
								<h4 class="border-b-[1px] border-black">{{ request.user.username }}</h4>
								<small class="font-bold">{{ request.user.profile.role }}</small>
							</div>
						</a>
						{% if not request.user.profile %}
						<li
							class="py-2 px-2 hover:text-blue-500 hover:bg-blue-50/50 rounded-md transition"
						>
						<a href="{% url 'account:profile' %}"
							 ><i class="fa-regular fa-arrow-right-to-bracket"></i>
								<span class="ml-1">create profile</span></a
							>
						</li>
						{% endif %}
						<li
							class="py-2 px-2 hover:text-blue-500 hover:bg-blue-50/50 rounded-md transition"
						>
						<a href="{% url 'account:logout' %}"
							 ><i class="fa-regular fa-arrow-right-from-bracket"></i>
								<span class="ml-1">logout</span></a
							>
						</li>
						{% else %}
						<li
							class="py-2 px-2 hover:text-blue-500 hover:bg-blue-50/50 rounded-md transition"
						>
						<a href="{% url 'account:login' %}"
							 ><i class="fa-regular fa-arrow-right-to-bracket"></i>
								<span class="ml-1">login</span></a
							>
						</li>
						<li
							class="py-2 px-2 hover:text-blue-500 hover:bg-blue-50/50 rounded-md transition"
						>
						<a href="{% url 'account:register' %}"
							 ><i class="fa-regular fa-user"></i>
								<span class="ml-1">register</span></a
							>
						</li>
						{% endif	%}
					</ul>
				</details>
				{% for nav in request.nav %}
				<details class="[&>summary>i]:open:rotate-180">
					<summary
						class="border-b font-bold py-2 px-2 flex items-center justify-between"
					>
						<h3>{{ nav.name }}</h3>
						<i class="fa-regular fa-chevron-down transition"></i>
					</summary>
					<ul class="my-1 text-gray-600 text-sm">
						{% for link in nav.links %}
						<li
							class="py-2 px-2 hover:text-blue-500 hover:bg-blue-50/50 rounded-md transition"
						>
							<a href="{{ link.url }}"
								>{{ link.icon|safe }}
								<span class="ml-1">{{ link.name }}</span></a
							>
						</li>
						{% endfor %}
					</ul>
				</details>
				{% endfor %}
			</div>
			{% if request.user.is_authenticated %}
			<div class="py-5 hover:text-blue-500">
				<a href="{% url 'account:settings' %}"><i class="fa-regular fa-gear mr-2"></i>setting</a>
			</div>
			{% endif %}
		</nav>
		<main
			class="transition peer-checked:bg-black/10 min-h-screen peer-checked:blur-xl max-w-[750px] m-auto bg-white"
		>
				{% block body %} {% endblock %}
		</main>
		<script></script>
	</body>
</html>

templates/skeleton/form.html
{% extends 'skeleton/base.html' %}
{% block body %}
<div class="min-h-screen bg-[#e3e3e3]">
	<div class="flex items-center justify-center p-10 font-bold text-lg">
		{{ title }}
	</div>
	{% if form.errors or error %}
	<dialog class="backdrop:backdrop-blur p-10 box-content scale-0 transition-all duration-300">
		<form method="dialog" class="flex-col flex items-center justify-center gap-2 rounded-sm">
			<div class="bg-red-50 rounded-md p-2">
				{% for t, error in form.errors.items %}
				<span>{{ t }}:</span>
				<p class="text-red-400 indent-2">{{ error }}</p>
				{% endfor %}
				<div>{{ error }}</div>
			</div>
			<button class="px-5 py-1 outline-none bg-blue-400 rounded-md shadow-md active:scale-95 active:shadow-none transition-all text-white border">ok</button>
		</form>
	</dialog>
	<script>
		let dialog = document.querySelector('dialog')
		dialog.showModal()
		dialog.classList.replace('scale-0', 'scale-100')
	</script>
	{% endif %}
	<form class="px-3 max-w-[500px] m-auto" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% for field in form %}
		<div class="bg-white border-t-2 border-blue-400 shadow-md rounded-md box-content p-5 mb-5">
			<div class="mb-3">
				<div class="[&_*]:text-red-200 text-sm">
					{{ field.errors }}
				</div>
				<h3 class="text-lg text-black/80">
					{{ field.label }}
					{% if field.field.required %}
					<span class="text-sm text-red-400">*</span>
					{% endif %}
				</h3>
				<p class="text-sm text-black/50">{{ field.help_text }}</p>
			</div>
			{% if field.field.widget.input_type == 'select' %}
			<select
				class="w-full h-10 rounded-md transition-all duration-300 outline-none border-[1px] hover:border-b-[2px] hover:border-blue-400"
				name="{{ field.name }}"
				{% if field.field.required %}
				required
				{% endif %}
			>
				{% for option in field.field.widget.choices %}
				<option value="{{ option.0 }}">{{ option.1 }}</option>
				{% endfor %}
			</select>
			{% else %}
			<label>
				<input
					name="{{ field.name }}"
					type="{{ field.field.widget.input_type }}"
					class="w-full outline-none border-b-[2px] focus:border-blue-400"
					{% if field.value  %}
					value="{{ field.value }}"
					{% endif %}
					{% if field.field.required %}
					required
					{% endif %}
					>

			</label>
			{% endif %}	
		</div>
		{% endfor %}
		<button class="px-3 py-2 bg-blue-400 rounded-md shadow-md active:scale-95 active:shadow-none transition-all text-white border">submit</button>
	</form>
</div>
{% endblock %}